SELECT INDEX_NAME, NON_UNIQUE, INDEX_TYPE, SEQ_IN_INDEX, COLUMN_NAME,
       SUB_PART, COLLATION, /*expression*/ AS EXPRESSION, /*visible*/ AS IS_VISIBLE
FROM information_schema.STATISTICS WHERE TABLE_SCHEMA=? AND TABLE_NAME=?
ORDER BY INDEX_NAME, SEQ_IN_INDEX
