SELECT TABLE_NAME, TABLE_TYPE, COALESCE(ENGINE,''), TABLE_COLLATION,
       TABLE_COMMENT, TABLE_ROWS, AUTO_INCREMENT, COALESCE(CREATE_OPTIONS,'')
FROM information_schema.TABLES WHERE TABLE_SCHEMA=? ORDER BY BINARY TABLE_NAME
