SELECT TRIGGER_NAME AS OBJECT_NAME, 'trigger' AS KIND
FROM information_schema.TRIGGERS WHERE TRIGGER_SCHEMA=?
UNION ALL SELECT ROUTINE_NAME, LOWER(ROUTINE_TYPE)
FROM information_schema.ROUTINES WHERE ROUTINE_SCHEMA=?
UNION ALL SELECT EVENT_NAME, 'event'
FROM information_schema.EVENTS WHERE EVENT_SCHEMA=?
UNION ALL SELECT DISTINCT TABLE_NAME, 'partition'
FROM information_schema.PARTITIONS WHERE TABLE_SCHEMA=? AND PARTITION_NAME IS NOT NULL
ORDER BY KIND, OBJECT_NAME
