use my2pg::{config::TargetConfig, postgres};
use std::collections::BTreeSet;
use tokio_postgres::{Client, Row};

const SEQUENCES: &str = include_str!("../../src/postgres/observed_sequences.sql");
const TRIGGERS: &str = include_str!("../../src/postgres/observed_triggers.sql");

fn required(name: &str) -> String {
    std::env::var(name).unwrap_or_else(|_| panic!("missing required {name}"))
}

fn config(schema: &str) -> TargetConfig {
    serde_json::from_value(serde_json::json!({
        "url_env":"MY2PG_POSTGRES_URL", "schema":schema, "ca_file":required("MY2PG_TLS_CA")
    }))
    .unwrap()
}

fn bound<'a>(rows: &'a [Row], name: &str) -> &'a Row {
    rows.iter()
        .find(|r| r.get::<_, String>("bound_column_name") == name)
        .unwrap_or_else(|| panic!("missing sequence bound to {name}"))
}

#[derive(Debug, PartialEq)]
enum ObservedState {
    Known(i64, bool),
    Unavailable(&'static str),
}

async fn state(client: &Client, row: &Row) -> ObservedState {
    if !row.get::<_, bool>("can_select") {
        return ObservedState::Unavailable("select_privilege_denied");
    }
    let sql = format!(
        "SELECT last_value,is_called FROM {}",
        postgres::qualified(
            &row.get::<_, String>("sequence_schema"),
            &row.get::<_, String>("sequence_name")
        )
    );
    let state = client.query_one(&sql, &[]).await.unwrap();
    ObservedState::Known(state.get(0), state.get(1))
}

// Fail on any alias/type mismatch, including nullable dependency endpoints.
fn decode_sequence_contract(row: &Row) {
    for key in ["sequence_oid", "sequence_type_oid"] {
        let _: u32 = row.get(key);
    }
    for key in [
        "sequence_schema",
        "sequence_name",
        "type_schema",
        "type_name",
        "sequence_owner_role",
        "bound_column_name",
        "bound_identity_mode",
    ] {
        let _: String = row.get(key);
    }
    let _: i16 = row.get("bound_column_ordinal");
    for key in ["owner_column_ordinal", "default_reference_ordinal"] {
        let _: Option<i16> = row.get(key);
    }
    for key in [
        "start_value",
        "increment_by",
        "min_value",
        "max_value",
        "cache_size",
    ] {
        let _: i64 = row.get(key);
    }
    for key in ["cycle", "can_alter", "can_use", "can_select", "can_update"] {
        let _: bool = row.get(key);
    }
    for key in [
        "bound_default_expression",
        "owner_table_schema",
        "owner_table_name",
        "owner_column_name",
        "ownership_dependency",
        "extension_name",
        "dependency_direction",
        "dependency_catalog",
        "dependency_kind",
        "dependent_catalog",
        "referenced_catalog",
        "dependent_type",
        "dependent_schema",
        "dependent_name",
        "dependent_identity",
        "referenced_type",
        "referenced_schema",
        "referenced_name",
        "referenced_identity",
        "default_reference_schema",
        "default_reference_table",
        "default_reference_column",
        "default_reference_expression",
    ] {
        let _: Option<String> = row.get(key);
    }
    for key in ["dependent_oid", "referenced_oid"] {
        let _: Option<u32> = row.get(key);
    }
    for key in ["dependent_sub_id", "referenced_sub_id"] {
        let _: Option<i32> = row.get(key);
    }
}

#[tokio::test]
#[ignore = "requires owned PostgreSQL16 TLS fixture"]
async fn native_sequence_ownership_dependencies_privileges_and_state_are_independent() {
    let target = postgres::connect(&config("t11_seq"), &required("MY2PG_POSTGRES_URL"))
        .await
        .unwrap();
    target.client.batch_execute(r#"
        CREATE SCHEMA t11_seq; CREATE SCHEMA t11_seq_other;
        CREATE SEQUENCE t11_seq."same,seq";
        CREATE SEQUENCE t11_seq_other."same,seq";
        CREATE SEQUENCE t11_seq.extension_seq;
        ALTER EXTENSION plpgsql ADD SEQUENCE t11_seq.extension_seq;
        CREATE TABLE t11_seq.rows (
            serial_id serial,
            by_default integer GENERATED BY DEFAULT AS IDENTITY,
            always_id bigint GENERATED ALWAYS AS IDENTITY,
            custom integer DEFAULT nextval('t11_seq."same,seq"'::regclass),
            other_custom integer DEFAULT nextval('t11_seq_other."same,seq"'::regclass),
            extension_value integer DEFAULT nextval('t11_seq.extension_seq'::regclass)
        );
        CREATE TABLE t11_seq.empty(n integer);
        CREATE TABLE t11_seq_other.external_user(id integer DEFAULT nextval('t11_seq."same,seq"'::regclass));
        CREATE VIEW t11_seq_other.sequence_view AS SELECT nextval('t11_seq."same,seq"'::regclass) AS id;
        CREATE FUNCTION t11_seq_other.use_sequence() RETURNS bigint LANGUAGE SQL
            RETURN nextval('t11_seq."same,seq"'::regclass);
        ALTER SEQUENCE t11_seq.rows_by_default_seq INCREMENT 3 MINVALUE 0 MAXVALUE 99 START 7 CACHE 4 CYCLE;
        SELECT setval('t11_seq.rows_by_default_seq',42,false);
        SELECT setval('t11_seq.rows_serial_id_seq',21,true);
        CREATE ROLE t11_seq_reader LOGIN PASSWORD 'catalog-only';
        GRANT USAGE ON SCHEMA t11_seq,t11_seq_other TO t11_seq_reader;
        GRANT SELECT,INSERT,UPDATE ON t11_seq.rows TO t11_seq_reader;
        GRANT SELECT,USAGE ON SEQUENCE t11_seq.rows_serial_id_seq TO t11_seq_reader;
        GRANT USAGE ON SEQUENCE t11_seq.rows_by_default_seq TO t11_seq_reader;
        CREATE ROLE t11_seq_owner LOGIN PASSWORD 'catalog-owner';
        GRANT USAGE,CREATE ON SCHEMA t11_seq TO t11_seq_owner;
        ALTER SEQUENCE t11_seq."same,seq" OWNER TO t11_seq_owner;
        REVOKE ALL ON SEQUENCE t11_seq."same,seq" FROM t11_seq_owner;
    "#).await.unwrap();
    target
        .client
        .batch_execute("BEGIN ISOLATION LEVEL REPEATABLE READ READ ONLY")
        .await
        .unwrap();
    let rows = target
        .client
        .query(SEQUENCES, &[&"t11_seq", &"rows"])
        .await
        .unwrap();
    assert!(!rows.is_empty());
    for row in &rows {
        decode_sequence_contract(row);
    }
    let columns: BTreeSet<_> = rows
        .iter()
        .map(|r| r.get::<_, String>("bound_column_name"))
        .collect();
    assert_eq!(
        columns,
        BTreeSet::from(
            [
                "serial_id",
                "by_default",
                "always_id",
                "custom",
                "other_custom",
                "extension_value"
            ]
            .map(String::from)
        )
    );
    let serial = bound(&rows, "serial_id");
    assert_eq!(
        serial
            .get::<_, Option<String>>("ownership_dependency")
            .as_deref(),
        Some("a")
    );
    assert_eq!(
        serial.get::<_, Option<i16>>("owner_column_ordinal"),
        Some(1)
    );
    assert_eq!(
        serial
            .get::<_, Option<String>>("owner_table_name")
            .as_deref(),
        Some("rows")
    );
    assert_eq!(serial.get::<_, String>("type_name"), "int4");
    assert_eq!(serial.get::<_, String>("bound_identity_mode"), "");
    let default = bound(&rows, "by_default");
    assert_eq!(
        default
            .get::<_, Option<String>>("ownership_dependency")
            .as_deref(),
        Some("i")
    );
    assert_eq!(default.get::<_, String>("bound_identity_mode"), "d");
    assert_eq!(default.get::<_, i64>("start_value"), 7);
    assert_eq!(default.get::<_, i64>("increment_by"), 3);
    assert_eq!(default.get::<_, i64>("min_value"), 0);
    assert_eq!(default.get::<_, i64>("max_value"), 99);
    assert_eq!(default.get::<_, i64>("cache_size"), 4);
    assert!(default.get::<_, bool>("cycle"));
    let always = bound(&rows, "always_id");
    assert_eq!(always.get::<_, String>("bound_identity_mode"), "a");
    assert_eq!(always.get::<_, String>("type_name"), "int8");
    let custom = bound(&rows, "custom");
    let other = bound(&rows, "other_custom");
    assert_eq!(
        custom.get::<_, String>("sequence_name"),
        other.get::<_, String>("sequence_name")
    );
    assert_ne!(
        custom.get::<_, u32>("sequence_oid"),
        other.get::<_, u32>("sequence_oid")
    );
    assert_eq!(other.get::<_, String>("sequence_schema"), "t11_seq_other");
    assert_eq!(
        custom.get::<_, Option<String>>("ownership_dependency"),
        None
    );
    assert!(rows.iter().any(|r| {
        r.get::<_, Option<String>>("default_reference_schema")
            .as_deref()
            == Some("t11_seq_other")
            && r.get::<_, Option<String>>("default_reference_table")
                .as_deref()
                == Some("external_user")
    }));
    for catalog in ["pg_catalog.pg_rewrite", "pg_catalog.pg_proc"] {
        assert!(
            rows.iter().any(|r| r
                .get::<_, Option<String>>("dependency_direction")
                .as_deref()
                == Some("incoming")
                && r.get::<_, Option<String>>("dependent_catalog").as_deref() == Some(catalog)),
            "missing external {catalog} edge"
        );
    }
    assert_eq!(
        bound(&rows, "extension_value")
            .get::<_, Option<String>>("extension_name")
            .as_deref(),
        Some("plpgsql")
    );
    assert_eq!(
        custom.get::<_, String>("sequence_owner_role"),
        "t11_seq_owner"
    );
    assert_eq!(
        state(&target.client, custom).await,
        ObservedState::Known(1, false)
    );
    let serial_before = state(&target.client, serial).await;
    let default_before = state(&target.client, default).await;
    assert_eq!(serial_before, ObservedState::Known(21, true));
    assert_eq!(default_before, ObservedState::Known(42, false));
    assert!(
        target
            .client
            .query(SEQUENCES, &[&"t11_seq", &"empty"])
            .await
            .unwrap()
            .is_empty()
    );
    assert_eq!(state(&target.client, serial).await, serial_before);
    assert_eq!(state(&target.client, default).await, default_before);
    target.client.batch_execute("ROLLBACK").await.unwrap();

    let mut reader_url = url::Url::parse(&required("MY2PG_POSTGRES_URL")).unwrap();
    reader_url.set_username("t11_seq_reader").unwrap();
    reader_url.set_password(Some("catalog-only")).unwrap();
    let reader = postgres::connect(&config("t11_seq"), reader_url.as_str())
        .await
        .unwrap();
    reader
        .client
        .batch_execute("BEGIN READ ONLY")
        .await
        .unwrap();
    let denied = reader
        .client
        .query(SEQUENCES, &[&"t11_seq", &"rows"])
        .await
        .unwrap();
    assert_eq!(
        denied
            .iter()
            .map(|r| r.get::<_, String>("bound_column_name"))
            .collect::<BTreeSet<_>>(),
        columns
    );
    let serial = bound(&denied, "serial_id");
    let default = bound(&denied, "by_default");
    assert!(serial.get::<_, bool>("can_select"));
    assert!(!serial.get::<_, bool>("can_update"));
    assert!(!serial.get::<_, bool>("can_alter"));
    assert!(default.get::<_, bool>("can_use"));
    assert!(!default.get::<_, bool>("can_select"));
    assert!(!default.get::<_, bool>("can_update"));
    assert!(
        denied.iter().any(|r| {
            r.get::<_, Option<String>>("dependency_catalog").as_deref()
                == Some("pg_catalog.pg_shdepend")
                && r.get::<_, Option<String>>("dependency_kind").as_deref() == Some("a")
                && r.get::<_, Option<String>>("referenced_catalog").as_deref()
                    == Some("pg_catalog.pg_authid")
                && r.get::<_, Option<String>>("referenced_name").as_deref()
                    == Some("t11_seq_reader")
                && r.get::<_, Option<String>>("referenced_type").as_deref() == Some("role")
        }),
        "shared ACL edges must survive restricted-role inspection"
    );
    assert!(
        denied.iter().any(|r| {
            r.get::<_, Option<String>>("dependency_catalog").as_deref()
                == Some("pg_catalog.pg_depend")
                && r.get::<_, Option<String>>("dependency_kind").as_deref() == Some("a")
                && r.get::<_, Option<String>>("referenced_catalog").as_deref()
                    == Some("pg_catalog.pg_class")
        }),
        "local automatic ownership must remain distinct from shared ACL a edges"
    );
    assert_eq!(
        state(&reader.client, default).await,
        ObservedState::Unavailable("select_privilege_denied")
    );
    assert_eq!(
        state(&reader.client, serial).await,
        ObservedState::Known(21, true)
    );
    assert!(
        reader
            .client
            .query_one("SELECT has_table_privilege('t11_seq.rows','INSERT')", &[])
            .await
            .unwrap()
            .get::<_, bool>(0)
    );
    reader.client.batch_execute("ROLLBACK").await.unwrap();
    let error = reader
        .client
        .query_one(
            "SELECT last_value,is_called FROM t11_seq.rows_by_default_seq",
            &[],
        )
        .await
        .unwrap_err();
    assert_eq!(error.code().unwrap().code(), "42501");
    reader.close().await.unwrap();
    reader_url.set_username("t11_seq_owner").unwrap();
    reader_url.set_password(Some("catalog-owner")).unwrap();
    let owner = postgres::connect(&config("t11_seq"), reader_url.as_str())
        .await
        .unwrap();
    let owner_rows = owner
        .client
        .query(SEQUENCES, &[&"t11_seq", &"rows"])
        .await
        .unwrap();
    let owner_sequence = bound(&owner_rows, "custom");
    assert!(owner_sequence.get::<_, bool>("can_alter"));
    for privilege in ["can_use", "can_select", "can_update"] {
        assert!(
            !owner_sequence.get::<_, bool>(privilege),
            "ownership must not fabricate {privilege}"
        );
    }
    assert!(owner_rows.iter().any(|r| {
        r.get::<_, Option<String>>("dependency_catalog").as_deref()
            == Some("pg_catalog.pg_shdepend")
            && r.get::<_, Option<String>>("dependency_kind").as_deref() == Some("o")
            && r.get::<_, Option<String>>("referenced_name").as_deref() == Some("t11_seq_owner")
    }));
    owner.close().await.unwrap();
    target.client.batch_execute("ALTER EXTENSION plpgsql DROP SEQUENCE t11_seq.extension_seq;DROP SCHEMA t11_seq_other CASCADE;DROP SCHEMA t11_seq CASCADE;DROP ROLE t11_seq_reader;DROP ROLE t11_seq_owner").await.unwrap();
    target.close().await.unwrap();
}

fn trigger<'a>(rows: &'a [Row], name: &str) -> &'a Row {
    rows.iter()
        .find(|r| r.get::<_, String>("trigger_name") == name)
        .unwrap()
}

fn decode_trigger_contract(row: &Row) {
    for key in [
        "scope",
        "trigger_name",
        "enabled",
        "function_schema",
        "function_name",
        "function_arguments",
        "function_identity",
        "function_definition",
        "function_language",
        "function_volatility",
        "function_owner_role",
    ] {
        let _: String = row.get(key);
    }
    for key in ["trigger_oid", "function_oid"] {
        let _: u32 = row.get(key);
    }
    for key in [
        "table_oid",
        "constraint_oid",
        "trigger_parent_oid",
        "dependent_oid",
        "referenced_oid",
    ] {
        let _: Option<u32> = row.get(key);
    }
    let _: Option<bool> = row.get("internal");
    let _: bool = row.get("function_security_definer");
    let _: Option<i16> = row.get("event_flags");
    for key in ["dependent_sub_id", "referenced_sub_id"] {
        let _: Option<i32> = row.get(key);
    }
    for key in ["event_tags", "function_config"] {
        let _: Option<Vec<String>> = row.get(key);
    }
    for key in [
        "table_schema",
        "table_name",
        "constraint_name",
        "definition",
        "event",
        "dependency_subject",
        "dependency_direction",
        "dependency_catalog",
        "dependency_kind",
        "dependent_catalog",
        "referenced_catalog",
        "dependent_type",
        "dependent_schema",
        "dependent_name",
        "dependent_identity",
        "referenced_type",
        "referenced_schema",
        "referenced_name",
        "referenced_identity",
    ] {
        let _: Option<String> = row.get(key);
    }
}

#[tokio::test]
#[ignore = "requires owned PostgreSQL16 TLS fixture"]
async fn native_trigger_headers_function_provenance_and_global_event_inventory_survive() {
    let target = postgres::connect(&config("t11_trig"), &required("MY2PG_POSTGRES_URL"))
        .await
        .unwrap();
    target.client.batch_execute(r#"
        CREATE SCHEMA t11_trig; CREATE SCHEMA t11_trig_other;
        CREATE TABLE t11_trig.parent(id integer PRIMARY KEY);
        CREATE TABLE t11_trig.rows(id integer REFERENCES t11_trig.parent(id));
        CREATE FUNCTION t11_trig.marker() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER
          SET search_path = pg_catalog AS $$ BEGIN RETURN NEW; END $$;
        CREATE FUNCTION t11_trig_other.marker() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RETURN NEW; END $$;
        CREATE TRIGGER ordinary BEFORE INSERT ON t11_trig.rows FOR EACH ROW EXECUTE FUNCTION t11_trig.marker();
        CREATE TRIGGER disabled BEFORE INSERT ON t11_trig.rows FOR EACH ROW EXECUTE FUNCTION t11_trig_other.marker();
        CREATE TRIGGER replica BEFORE INSERT ON t11_trig.rows FOR EACH ROW EXECUTE FUNCTION t11_trig.marker();
        CREATE TRIGGER always BEFORE INSERT ON t11_trig.rows FOR EACH ROW EXECUTE FUNCTION t11_trig.marker();
        ALTER TABLE t11_trig.rows DISABLE TRIGGER disabled;
        ALTER TABLE t11_trig.rows ENABLE REPLICA TRIGGER replica;
        ALTER TABLE t11_trig.rows ENABLE ALWAYS TRIGGER always;
        CREATE FUNCTION t11_trig_other.ddl_marker() RETURNS event_trigger LANGUAGE plpgsql AS $$ BEGIN RETURN; END $$;
        CREATE EVENT TRIGGER t11_global_enabled ON ddl_command_end WHEN TAG IN ('ALTER TABLE') EXECUTE FUNCTION t11_trig_other.ddl_marker();
        CREATE EVENT TRIGGER t11_global_disabled ON ddl_command_end EXECUTE FUNCTION t11_trig_other.ddl_marker();
        ALTER EVENT TRIGGER t11_global_disabled DISABLE;
        CREATE ROLE t11_trig_function_user;
        GRANT EXECUTE ON FUNCTION t11_trig.marker() TO t11_trig_function_user;
    "#).await.unwrap();
    target
        .client
        .batch_execute("BEGIN ISOLATION LEVEL REPEATABLE READ READ ONLY")
        .await
        .unwrap();
    let table = Some("rows");
    let rows = target
        .client
        .query(TRIGGERS, &[&"t11_trig", &table])
        .await
        .unwrap();
    for row in &rows {
        decode_trigger_contract(row);
    }
    for (name, enabled) in [
        ("ordinary", "O"),
        ("disabled", "D"),
        ("replica", "R"),
        ("always", "A"),
    ] {
        let row = trigger(&rows, name);
        assert_eq!(row.get::<_, String>("enabled"), enabled);
        assert_eq!(row.get::<_, Option<bool>>("internal"), Some(false));
        assert_eq!(row.get::<_, String>("scope"), "table");
        assert!(
            row.get::<_, Option<String>>("definition")
                .unwrap()
                .contains("CREATE TRIGGER")
        );
    }
    let ordinary = trigger(&rows, "ordinary");
    assert!(ordinary.get::<_, bool>("function_security_definer"));
    assert_eq!(
        ordinary.get::<_, Option<Vec<String>>>("function_config"),
        Some(vec!["search_path=pg_catalog".into()])
    );
    assert_eq!(
        ordinary.get::<_, String>("function_identity"),
        "t11_trig.marker()"
    );
    assert_eq!(ordinary.get::<_, String>("function_language"), "plpgsql");
    assert!(rows.iter().any(|r| {
        r.get::<_, String>("trigger_name") == "ordinary"
            && r.get::<_, Option<String>>("dependency_subject").as_deref() == Some("function")
            && r.get::<_, Option<String>>("dependency_catalog").as_deref()
                == Some("pg_catalog.pg_shdepend")
            && r.get::<_, Option<String>>("referenced_name").as_deref()
                == Some("t11_trig_function_user")
    }));
    let disabled = trigger(&rows, "disabled");
    assert_eq!(
        disabled.get::<_, String>("function_schema"),
        "t11_trig_other"
    );
    assert_ne!(
        disabled.get::<_, u32>("function_oid"),
        ordinary.get::<_, u32>("function_oid")
    );
    assert!(
        rows.iter()
            .any(|r| r.get::<_, Option<bool>>("internal") == Some(true)
                && r.get::<_, Option<u32>>("constraint_oid").is_some())
    );
    let header_count = target
        .client
        .query_one(
            "SELECT count(*) FROM pg_catalog.pg_trigger WHERE tgrelid='t11_trig.rows'::regclass",
            &[],
        )
        .await
        .unwrap()
        .get::<_, i64>(0);
    assert_eq!(
        rows.iter()
            .map(|r| r.get::<_, u32>("trigger_oid"))
            .collect::<BTreeSet<_>>()
            .len() as i64,
        header_count
    );
    assert!(
        target
            .client
            .query(TRIGGERS, &[&"t11_trig_other", &table])
            .await
            .unwrap()
            .is_empty()
    );
    let global: Option<&str> = None;
    let events = target
        .client
        .query(TRIGGERS, &[&"nonexistent_namespace", &global])
        .await
        .unwrap();
    for row in &events {
        decode_trigger_contract(row);
    }
    assert_eq!(
        trigger(&events, "t11_global_enabled").get::<_, String>("enabled"),
        "O"
    );
    assert_eq!(
        trigger(&events, "t11_global_disabled").get::<_, String>("enabled"),
        "D"
    );
    assert_eq!(
        trigger(&events, "t11_global_enabled").get::<_, Option<Vec<String>>>("event_tags"),
        Some(vec!["ALTER TABLE".into()])
    );
    assert_eq!(
        trigger(&events, "t11_global_enabled")
            .get::<_, Option<String>>("event")
            .as_deref(),
        Some("ddl_command_end")
    );
    for row in &events {
        assert_eq!(row.get::<_, String>("scope"), "event");
        assert_eq!(row.get::<_, Option<bool>>("internal"), None);
        assert_eq!(row.get::<_, Option<u32>>("table_oid"), None);
    }
    let event_count = target
        .client
        .query_one("SELECT count(*) FROM pg_catalog.pg_event_trigger", &[])
        .await
        .unwrap()
        .get::<_, i64>(0);
    assert_eq!(
        events
            .iter()
            .map(|r| r.get::<_, u32>("trigger_oid"))
            .collect::<BTreeSet<_>>()
            .len() as i64,
        event_count
    );
    assert_eq!(
        target
            .client
            .query_one("SELECT count(*) FROM t11_trig.rows", &[])
            .await
            .unwrap()
            .get::<_, i64>(0),
        0
    );
    target.client.batch_execute("ROLLBACK;DROP EVENT TRIGGER t11_global_enabled;DROP EVENT TRIGGER t11_global_disabled;DROP SCHEMA t11_trig CASCADE;DROP SCHEMA t11_trig_other CASCADE;DROP ROLE t11_trig_function_user").await.unwrap();
    target.close().await.unwrap();
}
