use my2pg::{config::TargetConfig, postgres};
use tokio_postgres::Row;

const COLUMNS: &str = include_str!("../../src/postgres/observed_columns.sql");
const INDEXES: &str = include_str!("../../src/postgres/observed_indexes.sql");
const CONSTRAINTS: &str = include_str!("../../src/postgres/observed_constraints.sql");

fn required(name: &str) -> String {
    std::env::var(name).unwrap_or_else(|_| panic!("missing required {name}"))
}

fn named<'a>(rows: &'a [Row], field: &str, name: &str) -> Vec<&'a Row> {
    rows.iter()
        .filter(|row| row.get::<_, String>(field) == name)
        .collect()
}

#[tokio::test]
#[ignore = "requires owned PostgreSQL16 TLS fixture"]
async fn native_failed_concurrent_index_retains_real_invalid_state() {
    let config: TargetConfig = serde_json::from_value(serde_json::json!({
        "url_env":"MY2PG_POSTGRES_URL","schema":"t11_catalog_invalid","ca_file":required("MY2PG_TLS_CA")
    })).unwrap();
    let target = postgres::connect(&config, &required("MY2PG_POSTGRES_URL"))
        .await
        .unwrap();
    target.client.batch_execute("DROP SCHEMA IF EXISTS t11_catalog_invalid CASCADE;CREATE SCHEMA t11_catalog_invalid;CREATE TABLE t11_catalog_invalid.duplicates(a integer);INSERT INTO t11_catalog_invalid.duplicates VALUES(1),(1)").await.unwrap();
    let error = target
        .client
        .batch_execute(
            "CREATE UNIQUE INDEX CONCURRENTLY failed_unique ON t11_catalog_invalid.duplicates(a)",
        )
        .await
        .unwrap_err();
    assert_eq!(error.code().unwrap().code(), "23505");
    target
        .client
        .batch_execute("BEGIN READ ONLY")
        .await
        .unwrap();
    let rows = target
        .client
        .query(INDEXES, &[&"t11_catalog_invalid", &"duplicates"])
        .await
        .unwrap();
    assert_eq!(
        rows.len(),
        1,
        "failed concurrent build must remain inventoried"
    );
    let row = &rows[0];
    assert_eq!(row.get::<_, String>("index_name"), "failed_unique");
    assert_eq!(
        row.get::<_, Option<String>>("column_name"),
        Some("a".into())
    );
    assert!(row.get::<_, bool>("is_unique"));
    assert!(!row.get::<_, bool>("valid"));
    assert!(!row.get::<_, bool>("ready"));
    assert!(row.get::<_, bool>("live"));
    assert_eq!(row.get::<_, Option<String>>("constraint_name"), None);
    target.client.batch_execute("ROLLBACK").await.unwrap();
    assert_eq!(
        target
            .client
            .query_one("SELECT COUNT(*) FROM t11_catalog_invalid.duplicates", &[])
            .await
            .unwrap()
            .get::<_, i64>(0),
        2
    );
    target
        .client
        .batch_execute("DROP SCHEMA t11_catalog_invalid CASCADE")
        .await
        .unwrap();
    target.close().await.unwrap();
}

#[tokio::test]
#[ignore = "requires owned PostgreSQL16 TLS fixture"]
async fn native_observed_columns_indexes_constraints_are_ordered_typed_and_read_only() {
    let config: TargetConfig = serde_json::from_value(serde_json::json!({
        "url_env":"MY2PG_POSTGRES_URL","schema":"t11_catalog","ca_file":required("MY2PG_TLS_CA")
    }))
    .unwrap();
    let target = postgres::connect(&config, &required("MY2PG_POSTGRES_URL"))
        .await
        .unwrap();
    target.client.batch_execute(r#"
        DROP SCHEMA IF EXISTS t11_catalog CASCADE;
        DROP SCHEMA IF EXISTS t11_catalog_other CASCADE;
        CREATE SCHEMA t11_catalog;
        CREATE SCHEMA t11_catalog_other;
        CREATE TYPE t11_catalog."State Type" AS ENUM ('','z','a');
        CREATE TABLE t11_catalog.parent (
            "first,key" integer NOT NULL,
            "SecondKey" integer NOT NULL,
            id integer GENERATED BY DEFAULT AS IDENTITY,
            always_id integer GENERATED ALWAYS AS IDENTITY,
            amount numeric(20,4) DEFAULT 1.2500,
            note varchar(30) COLLATE "C" DEFAULT 'quote''界',
            generated_value integer GENERATED ALWAYS AS ("SecondKey"+1) STORED,
            choice t11_catalog."State Type" DEFAULT 'z',
            span int4range,
            CONSTRAINT reversed_pk PRIMARY KEY("SecondKey","first,key"),
            CONSTRAINT deferred_pair UNIQUE("first,key","SecondKey") DEFERRABLE INITIALLY DEFERRED,
            CONSTRAINT range_exclusion EXCLUDE USING gist (span WITH &&)
        );
        COMMENT ON COLUMN t11_catalog.parent.note IS 'column ''quote'' 界';
        CREATE INDEX same_name ON t11_catalog.parent("SecondKey" DESC NULLS LAST,"first,key") INCLUDE(note) WHERE note IS NOT NULL;
        CREATE INDEX pattern_idx ON t11_catalog.parent(note COLLATE "C" varchar_pattern_ops);
        CREATE UNIQUE INDEX null_eq ON t11_catalog.parent(amount) NULLS NOT DISTINCT;
        CREATE INDEX expression_idx ON t11_catalog.parent((lower(note)));
        ALTER TABLE t11_catalog.parent ADD COLUMN matrix integer[][];
        ALTER TABLE t11_catalog.parent ADD COLUMN dropped_column integer;
        ALTER TABLE t11_catalog.parent DROP COLUMN dropped_column;
        CREATE TABLE t11_catalog_other.parent(a integer,b integer);
        CREATE INDEX same_name ON t11_catalog_other.parent(a,b);
        INSERT INTO t11_catalog.parent("first,key","SecondKey",span) VALUES(11,1,'[1,3)');
        CREATE TABLE t11_catalog.child("remote second" integer,"remote,first" integer,qty integer);
        INSERT INTO t11_catalog.child VALUES(999,999,-1);
        ALTER TABLE t11_catalog.child ADD CONSTRAINT invalid_fk FOREIGN KEY("remote second","remote,first") REFERENCES t11_catalog.parent("SecondKey","first,key") MATCH FULL ON UPDATE CASCADE ON DELETE SET NULL("remote second") DEFERRABLE INITIALLY DEFERRED NOT VALID;
        ALTER TABLE t11_catalog.child ADD CONSTRAINT invalid_check CHECK(qty>0) NO INHERIT NOT VALID;
        ALTER TABLE t11_catalog.child ADD CONSTRAINT constant_check CHECK(1>0) NOT VALID;
    "#).await.unwrap();
    let state_before = target
        .client
        .query_one(
            "SELECT last_value,is_called FROM t11_catalog.parent_id_seq",
            &[],
        )
        .await
        .unwrap();
    let state_before = (
        state_before.get::<_, i64>(0),
        state_before.get::<_, bool>(1),
    );
    target
        .client
        .batch_execute("BEGIN ISOLATION LEVEL REPEATABLE READ READ ONLY")
        .await
        .unwrap();
    let schema = "t11_catalog";
    let columns = target
        .client
        .query(COLUMNS, &[&schema, &"parent"])
        .await
        .unwrap();
    assert_eq!(
        columns
            .iter()
            .map(|r| r.get::<_, String>("name"))
            .collect::<Vec<_>>(),
        [
            "first,key",
            "SecondKey",
            "id",
            "always_id",
            "amount",
            "note",
            "generated_value",
            "choice",
            "span",
            "matrix"
        ]
    );
    assert_eq!(
        columns
            .iter()
            .map(|r| r.get::<_, i16>("ordinal"))
            .collect::<Vec<_>>(),
        (1..=10).collect::<Vec<i16>>()
    );
    let id = named(&columns, "name", "id")[0];
    assert_eq!(id.get::<_, String>("identity_mode"), "d");
    assert_eq!(id.get::<_, Option<String>>("default_expression"), None);
    assert_eq!(
        named(&columns, "name", "always_id")[0].get::<_, String>("identity_mode"),
        "a"
    );
    let amount = named(&columns, "name", "amount")[0];
    assert_eq!(amount.get::<_, String>("data_type"), "numeric(20,4)");
    assert_eq!(
        amount.get::<_, Option<String>>("default_expression"),
        Some("1.2500".into())
    );
    assert_eq!(
        (
            amount.get::<_, String>("type_schema"),
            amount.get::<_, String>("type_name")
        ),
        ("pg_catalog".into(), "numeric".into())
    );
    assert!(amount.get::<_, i32>("type_modifier") > 0);
    assert_eq!(amount.get::<_, i16>("array_dimensions"), 0);
    assert!(amount.get::<_, bool>("nullable"));
    let matrix = named(&columns, "name", "matrix")[0];
    assert_eq!(matrix.get::<_, String>("data_type"), "integer[]");
    assert_eq!(matrix.get::<_, i16>("array_dimensions"), 2);
    let note = named(&columns, "name", "note")[0];
    assert_eq!(
        note.get::<_, Option<String>>("comment"),
        Some("column 'quote' 界".into())
    );
    assert_eq!(
        note.get::<_, Option<String>>("collation_schema"),
        Some("pg_catalog".into())
    );
    assert_eq!(
        note.get::<_, Option<String>>("collation_name"),
        Some("C".into())
    );
    assert_eq!(
        note.get::<_, Option<bool>>("collation_deterministic"),
        Some(true)
    );
    assert!(
        note.get::<_, Option<String>>("default_expression")
            .unwrap()
            .contains("quote''界")
    );
    let generated = named(&columns, "name", "generated_value")[0];
    assert_eq!(generated.get::<_, String>("generated_kind"), "s");
    assert_eq!(
        generated.get::<_, Option<String>>("default_expression"),
        None
    );
    assert!(
        generated
            .get::<_, Option<String>>("generation_expression")
            .unwrap()
            .contains("\"SecondKey\" + 1")
    );
    assert_eq!(
        named(&columns, "name", "choice")[0].get::<_, String>("type_name"),
        "State Type"
    );
    assert_eq!(
        named(&columns, "name", "choice")[0].get::<_, String>("type_schema"),
        schema
    );
    let indexes = target
        .client
        .query(INDEXES, &[&schema, &"parent"])
        .await
        .unwrap();
    let shared = named(&indexes, "index_name", "same_name");
    assert_eq!(
        shared.len(),
        3,
        "other-schema index must not multiply parts"
    );
    assert_eq!(
        shared
            .iter()
            .map(|r| r.get::<_, i64>("ordinal"))
            .collect::<Vec<_>>(),
        [1, 2, 3]
    );
    assert_eq!(
        shared
            .iter()
            .map(|r| r.get::<_, Option<String>>("column_name"))
            .collect::<Vec<_>>(),
        [
            Some("SecondKey".into()),
            Some("first,key".into()),
            Some("note".into())
        ]
    );
    assert_eq!(
        shared
            .iter()
            .map(|r| r.get::<_, bool>("included"))
            .collect::<Vec<_>>(),
        [false, false, true]
    );
    assert_eq!(shared[0].get::<_, Option<bool>>("descending"), Some(true));
    assert_eq!(shared[0].get::<_, Option<bool>>("nulls_first"), Some(false));
    assert_eq!(shared[2].get::<_, Option<bool>>("descending"), None);
    assert_eq!(
        shared[2].get::<_, Option<String>>("operator_class_name"),
        None
    );
    assert_eq!(
        shared[0].get::<_, Option<String>>("predicate"),
        Some("(note IS NOT NULL)".into())
    );
    assert_eq!(shared[0].get::<_, String>("index_schema"), schema);
    assert_eq!(shared[0].get::<_, String>("table_schema"), schema);
    assert_eq!(shared[0].get::<_, String>("table_name"), "parent");
    let index_oid = shared[0].get::<_, u32>("index_oid");
    assert!(
        shared
            .iter()
            .all(|r| r.get::<_, u32>("index_oid") == index_oid)
    );
    let other = target
        .client
        .query(INDEXES, &[&"t11_catalog_other", &"parent"])
        .await
        .unwrap();
    assert_eq!(other.len(), 2);
    assert_ne!(other[0].get::<_, u32>("index_oid"), index_oid);
    let pk = named(&indexes, "index_name", "reversed_pk");
    assert_eq!(
        pk.iter()
            .map(|r| r.get::<_, Option<String>>("column_name"))
            .collect::<Vec<_>>(),
        [Some("SecondKey".into()), Some("first,key".into())]
    );
    assert!(pk.iter().all(|r| r.get::<_, bool>("is_primary")
        && r.get::<_, bool>("is_unique")
        && r.get::<_, bool>("valid")
        && r.get::<_, bool>("ready")
        && r.get::<_, bool>("live")));
    let deferred = named(&indexes, "index_name", "deferred_pair");
    assert!(!deferred[0].get::<_, bool>("immediate"));
    assert_eq!(
        deferred[0].get::<_, Option<bool>>("constraint_deferrable"),
        Some(true)
    );
    assert_eq!(
        deferred[0].get::<_, Option<bool>>("constraint_initially_deferred"),
        Some(true)
    );
    assert!(named(&indexes, "index_name", "null_eq")[0].get::<_, bool>("nulls_not_distinct"));
    let pattern = named(&indexes, "index_name", "pattern_idx")[0];
    assert_eq!(
        pattern.get::<_, Option<String>>("operator_class_name"),
        Some("varchar_pattern_ops".into())
    );
    assert_eq!(
        pattern.get::<_, Option<bool>>("default_operator_class"),
        Some(false)
    );
    assert_eq!(
        pattern.get::<_, Option<String>>("collation_name"),
        Some("C".into())
    );
    let expression = named(&indexes, "index_name", "expression_idx")[0];
    assert_eq!(expression.get::<_, Option<String>>("column_name"), None);
    assert!(
        expression
            .get::<_, Option<String>>("expression")
            .unwrap()
            .starts_with("lower(")
    );
    let parent_constraints = target
        .client
        .query(CONSTRAINTS, &[&schema, &"parent"])
        .await
        .unwrap();
    let excluded = named(&parent_constraints, "name", "range_exclusion");
    assert_eq!(excluded.len(), 1);
    assert_eq!(excluded[0].get::<_, String>("kind"), "x");
    assert!(
        excluded[0]
            .get::<_, String>("definition")
            .contains("EXCLUDE USING gist")
    );
    let child_constraints = target
        .client
        .query(CONSTRAINTS, &[&schema, &"child"])
        .await
        .unwrap();
    let fk = named(&child_constraints, "name", "invalid_fk");
    assert_eq!(fk.len(), 2);
    assert_eq!(
        fk.iter()
            .map(|r| r.get::<_, Option<String>>("column_name"))
            .collect::<Vec<_>>(),
        [Some("remote second".into()), Some("remote,first".into())]
    );
    assert_eq!(
        fk.iter()
            .map(|r| r.get::<_, Option<String>>("referenced_column"))
            .collect::<Vec<_>>(),
        [Some("SecondKey".into()), Some("first,key".into())]
    );
    assert!(fk.iter().all(|r| !r.get::<_, bool>("validated")
        && r.get::<_, bool>("deferrable")
        && r.get::<_, bool>("initially_deferred")));
    assert_eq!(fk[0].get::<_, String>("match_type"), "f");
    assert_eq!(fk[0].get::<_, String>("update_action"), "c");
    assert_eq!(fk[0].get::<_, String>("delete_action"), "n");
    assert_eq!(
        fk[0].get::<_, Option<Vec<String>>>("delete_set_columns"),
        Some(vec!["remote second".into()])
    );
    assert_eq!(
        fk[0].get::<_, Option<String>>("referenced_schema"),
        Some(schema.into())
    );
    assert_eq!(
        fk[0].get::<_, Option<String>>("supporting_index_name"),
        Some("reversed_pk".into())
    );
    for operator in ["pk_fk_operator", "pk_pk_operator", "fk_fk_operator"] {
        assert!(
            fk[0]
                .get::<_, Option<String>>(operator)
                .unwrap()
                .contains("pg_catalog")
        );
    }
    let check = named(&child_constraints, "name", "invalid_check")[0];
    assert_eq!(check.get::<_, String>("kind"), "c");
    assert!(!check.get::<_, bool>("validated"));
    assert!(check.get::<_, bool>("no_inherit"));
    assert_eq!(
        check.get::<_, Option<String>>("column_name"),
        Some("qty".into())
    );
    let constant = named(&child_constraints, "name", "constant_check");
    assert_eq!(
        constant.len(),
        1,
        "constant check header cannot disappear with empty conkey"
    );
    assert_eq!(constant[0].get::<_, Option<i64>>("ordinal"), None);
    assert!(!constant[0].get::<_, bool>("validated"));
    assert!(
        target
            .client
            .query(COLUMNS, &[&schema, &"missing"])
            .await
            .unwrap()
            .is_empty()
    );
    target.client.batch_execute("ROLLBACK").await.unwrap();
    let state_after = target
        .client
        .query_one(
            "SELECT last_value,is_called FROM t11_catalog.parent_id_seq",
            &[],
        )
        .await
        .unwrap();
    assert_eq!(
        state_before,
        (state_after.get::<_, i64>(0), state_after.get::<_, bool>(1))
    );
    let parent_values = target
        .client
        .query_one(
            "SELECT \"first,key\",\"SecondKey\",generated_value FROM t11_catalog.parent",
            &[],
        )
        .await
        .unwrap();
    assert_eq!(
        (
            parent_values.get::<_, i32>(0),
            parent_values.get::<_, i32>(1),
            parent_values.get::<_, i32>(2)
        ),
        (11, 1, 2)
    );
    assert_eq!(
        target
            .client
            .query_one("SELECT qty FROM t11_catalog.child", &[])
            .await
            .unwrap()
            .get::<_, i32>(0),
        -1
    );
    target
        .client
        .batch_execute("DROP SCHEMA t11_catalog CASCADE;DROP SCHEMA t11_catalog_other CASCADE")
        .await
        .unwrap();
    target.close().await.unwrap();
}
