//! Data-only truncate replaces selected rows and resets its existing identity from MySQL.
use my2pg::{config::MigrationConfig, mysql, postgres};
use mysql_async::prelude::Queryable;
use std::{env, fs, path::Path, process::Command};

fn required(name: &str) -> String {
    env::var(name).unwrap_or_else(|_| panic!("missing native fixture {name}"))
}

fn migration_config(schema: &str, source_table: &str, report_dir: &Path) -> MigrationConfig {
    serde_json::from_value(serde_json::json!({
        "version": 1,
        "source": {
            "url_env": "MY2PG_MYSQL_URL",
            "ca_file": required("MY2PG_TLS_CA"),
            "consistency": "frozen"
        },
        "target": {
            "url_env": "MY2PG_POSTGRES_URL",
            "ca_file": required("MY2PG_TLS_CA"),
            "schema": schema,
            "on_existing": "truncate"
        },
        "migration": {
            "mode": "data_only",
            "reset_sequences": true,
            "batch_rows": 2,
            "batch_bytes": 4096,
            "max_row_bytes": 1024,
            "memory_bytes": 262144
        },
        "tables": {
            "include": [source_table],
            "rename": [{"source": source_table, "target": "rows"}]
        },
        "report": {
            "directory": report_dir,
            "console": "json",
            "progress": "never"
        }
    }))
    .unwrap()
}

async fn run(config: &MigrationConfig, directory: &Path) -> std::process::Output {
    let path = directory.join("data-only-truncate-reset.toml");
    fs::write(&path, toml::to_string(config).unwrap()).unwrap();
    tokio::task::spawn_blocking(move || {
        Command::new(env!("CARGO_BIN_EXE_my2pg"))
            .arg("run")
            .arg(path)
            .args(["--output", "json", "--progress", "never"])
            .output()
            .unwrap()
    })
    .await
    .unwrap()
}

#[tokio::test]
#[ignore = "requires owned Oracle MySQL/PostgreSQL TLS fixtures"]
async fn native_data_only_truncate_resets_identity_after_copy_and_preserves_source_and_sentinels() {
    let suffix = std::process::id();
    let schema = format!("t11_truncate_reset_{suffix}");
    let outside_schema = format!("t11_truncate_reset_outside_{suffix}");
    let source_table = format!("T11TruncateReset{suffix}");
    let source_sentinel = format!("T11TruncateSentinel{suffix}");
    let directory = env::temp_dir().join(format!("my2pg-t11-truncate-reset-{suffix}"));
    fs::create_dir_all(&directory).unwrap();

    let source_config: my2pg::config::SourceConfig = serde_json::from_value(serde_json::json!({
        "url_env": "MY2PG_MYSQL_URL",
        "ca_file": required("MY2PG_TLS_CA"),
        "consistency": "frozen"
    }))
    .unwrap();
    let mut source = mysql::connect(&source_config, &required("MY2PG_MYSQL_ROOT_URL"), 1024)
        .await
        .unwrap();
    let source_ident = mysql::quote_ident(&source_table);
    let sentinel_ident = mysql::quote_ident(&source_sentinel);
    source
        .query_drop(format!(
            "DROP TABLE IF EXISTS {source_ident}, {sentinel_ident}"
        ))
        .await
        .unwrap();
    source
        .query_drop(format!(
            "CREATE TABLE {source_ident}(id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, value INT NOT NULL) ENGINE=InnoDB AUTO_INCREMENT=42"
        ))
        .await
        .unwrap();
    source
        .query_drop(format!(
            "INSERT INTO {source_ident}(id,value) VALUES(1,11),(2,22)"
        ))
        .await
        .unwrap();
    source
        .query_drop(format!(
            "CREATE TABLE {sentinel_ident}(value VARCHAR(40) NOT NULL); INSERT INTO {sentinel_ident} VALUES('source intact')"
        ))
        .await
        .unwrap();
    let source_next: Option<u64> = source
        .exec_first(
            "SELECT AUTO_INCREMENT FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=?",
            (&source_table,),
        )
        .await
        .unwrap()
        .unwrap();
    assert_eq!(source_next, Some(42), "source AUTO_INCREMENT fixture");

    let target_config: my2pg::config::TargetConfig = serde_json::from_value(serde_json::json!({
        "url_env": "MY2PG_POSTGRES_URL",
        "ca_file": required("MY2PG_TLS_CA"),
        "schema": schema
    }))
    .unwrap();
    let target = postgres::connect(&target_config, &required("MY2PG_POSTGRES_URL"))
        .await
        .unwrap();
    let target_ns = postgres::quote_ident(&schema);
    let outside_ns = postgres::quote_ident(&outside_schema);
    target
        .client
        .batch_execute(&format!(
            "DROP SCHEMA IF EXISTS {target_ns} CASCADE; DROP SCHEMA IF EXISTS {outside_ns} CASCADE; CREATE SCHEMA {target_ns}; CREATE SCHEMA {outside_ns}; CREATE TABLE {target_ns}.rows(id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, value integer NOT NULL, CONSTRAINT target_positive CHECK(value>0)); INSERT INTO {target_ns}.rows VALUES(900,900); CREATE TABLE {outside_ns}.sentinel(id integer PRIMARY KEY, payload text NOT NULL); INSERT INTO {outside_ns}.sentinel VALUES(7,'keep me')"
        ))
        .await
        .unwrap();
    let relation = postgres::qualified(&schema, "rows");
    let relation_name = format!("{schema}.rows");
    let sequence_before: String = target
        .client
        .query_one(
            "SELECT pg_catalog.pg_get_serial_sequence($1,'id')",
            &[&relation_name],
        )
        .await
        .unwrap()
        .get(0);
    let check_oid: u32 = target
        .client
        .query_one(
            "SELECT oid FROM pg_catalog.pg_constraint WHERE conrelid=$1::text::regclass AND conname='target_positive'",
            &[&relation],
        )
        .await
        .unwrap()
        .get(0);
    target
        .client
        .batch_execute(&format!(
            "SELECT pg_catalog.setval('{}'::regclass,1,false)",
            sequence_before.replace('\'', "''")
        ))
        .await
        .unwrap();
    let sentinel_oid: u32 = target
        .client
        .query_one(
            "SELECT c.oid FROM pg_catalog.pg_class c JOIN pg_catalog.pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname=$1 AND c.relname='sentinel'",
            &[&outside_schema],
        )
        .await
        .unwrap()
        .get(0);

    let migration = migration_config(&schema, &source_table, &directory.join("runs"));
    let output = run(&migration, &directory).await;
    assert!(
        output.status.success(),
        "data-only truncate failed: stdout={} stderr={}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );

    let rows = target
        .client
        .query(&format!("SELECT id,value FROM {relation} ORDER BY id"), &[])
        .await
        .unwrap();
    assert_eq!(
        rows.iter()
            .map(|row| (row.get::<_, i32>(0), row.get::<_, i32>(1)))
            .collect::<Vec<_>>(),
        [(1, 11), (2, 22)],
        "truncate removes the prior target row and loads only selected source rows"
    );
    let identity_row = target
        .client
        .query_one(
            "SELECT a.attidentity::text, pg_catalog.format_type(a.atttypid,a.atttypmod), a.attnotnull FROM pg_catalog.pg_attribute a WHERE a.attrelid=$1::text::regclass AND a.attname='id'",
            &[&relation],
        )
        .await
        .unwrap();
    let identity = (
        identity_row.get::<_, String>(0),
        identity_row.get::<_, String>(1),
        identity_row.get::<_, bool>(2),
    );
    assert_eq!(identity, ("d".into(), "integer".into(), true));
    let has_primary_key: bool = target
        .client
        .query_one(
            "SELECT EXISTS(SELECT 1 FROM pg_catalog.pg_index WHERE indrelid=$1::text::regclass AND indisprimary)",
            &[&relation],
        )
        .await
        .unwrap()
        .get(0);
    assert!(
        has_primary_key,
        "data-only truncate retains the target primary key"
    );
    let check_oid_after: u32 = target
        .client
        .query_one(
            "SELECT oid FROM pg_catalog.pg_constraint WHERE conrelid=$1::text::regclass AND conname='target_positive'",
            &[&relation],
        )
        .await
        .unwrap()
        .get(0);
    assert_eq!(
        check_oid_after, check_oid,
        "truncate retains target constraints"
    );
    let sequence_after: String = target
        .client
        .query_one(
            "SELECT pg_catalog.pg_get_serial_sequence($1,'id')",
            &[&relation_name],
        )
        .await
        .unwrap()
        .get(0);
    assert_eq!(
        sequence_after, sequence_before,
        "identity ownership is retained"
    );
    let sequence_row = target
        .client
        .query_one(
            &format!("SELECT last_value,is_called FROM {sequence_after}"),
            &[],
        )
        .await
        .unwrap();
    let sequence_state = (
        sequence_row.get::<_, i64>(0),
        sequence_row.get::<_, bool>(1),
    );
    assert_eq!(sequence_state, (42, false));
    let next_id: i64 = target
        .client
        .query_one("SELECT nextval($1::text::regclass)", &[&sequence_after])
        .await
        .unwrap()
        .get(0);
    assert_eq!(next_id, 42, "the next generated identity uses source state");

    let source_rows: Vec<(i32, i32)> = source
        .exec(
            format!("SELECT id,value FROM {source_ident} ORDER BY id"),
            (),
        )
        .await
        .unwrap();
    assert_eq!(source_rows, [(1, 11), (2, 22)]);
    let source_next_after: Option<u64> = source
        .exec_first(
            "SELECT AUTO_INCREMENT FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=?",
            (&source_table,),
        )
        .await
        .unwrap()
        .unwrap();
    assert_eq!(
        source_next_after,
        Some(42),
        "migration preserves source identity state"
    );
    let source_sentinel_value: String = source
        .query_first(format!("SELECT value FROM {sentinel_ident}"))
        .await
        .unwrap()
        .unwrap();
    assert_eq!(source_sentinel_value, "source intact");
    let sentinel_row = target
        .client
        .query_one(
            &format!("SELECT c.oid, s.payload FROM pg_catalog.pg_class c JOIN pg_catalog.pg_namespace n ON n.oid=c.relnamespace JOIN {outside_ns}.sentinel s ON true WHERE n.nspname=$1 AND c.relname='sentinel'"),
            &[&outside_schema],
        )
        .await
        .unwrap();
    let sentinel = (
        sentinel_row.get::<_, u32>(0),
        sentinel_row.get::<_, String>(1),
    );
    assert_eq!(sentinel, (sentinel_oid, "keep me".into()));

    target
        .client
        .batch_execute(&format!(
            "DROP SCHEMA {target_ns} CASCADE; DROP SCHEMA {outside_ns} CASCADE"
        ))
        .await
        .unwrap();
    source
        .query_drop(format!("DROP TABLE {source_ident}, {sentinel_ident}"))
        .await
        .unwrap();
    target.close().await.unwrap();
    source.disconnect().await.unwrap();
}
