use my2pg::{config::TargetConfig, postgres};

fn required(name: &str) -> String {
    std::env::var(name).unwrap_or_else(|_| panic!("missing required {name}"))
}

#[tokio::test]
#[ignore = "requires owned PostgreSQL TLS fixture"]
async fn public_inspector_retains_typed_observations_and_known_empty_without_mutation() {
    let config: TargetConfig = serde_json::from_value(serde_json::json!({
        "url_env":"MY2PG_POSTGRES_URL","schema":"t11 decoder","ca_file":required("MY2PG_TLS_CA")
    }))
    .unwrap();
    let mut target = postgres::connect(&config, &required("MY2PG_POSTGRES_URL"))
        .await
        .unwrap();
    target.client.batch_execute(r#"
        DROP SCHEMA IF EXISTS "t11 decoder" CASCADE;
        DROP SCHEMA IF EXISTS t11_decoder_other CASCADE;
        CREATE SCHEMA "t11 decoder";
        CREATE SCHEMA t11_decoder_other;
        CREATE TYPE "t11 decoder"."State Type" AS ENUM ('z','a');
        CREATE DOMAIN "t11 decoder".positive AS integer CHECK(VALUE>0);
        CREATE TABLE "t11 decoder".parent (
            "first,key" integer,
            "SecondKey" integer,
            id integer GENERATED BY DEFAULT AS IDENTITY,
            always_id integer GENERATED ALWAYS AS IDENTITY,
            value "t11 decoder"."State Type" DEFAULT 'z',
            note text COLLATE "C" DEFAULT 'quote''界',
            matrix integer[][],
            domain_value "t11 decoder".positive,
            generated_value integer GENERATED ALWAYS AS ("SecondKey"+1) STORED,
            CONSTRAINT reversed_pk PRIMARY KEY("SecondKey","first,key")
        );
        COMMENT ON TABLE "t11 decoder".parent IS 'table ''quote'' 界';
        COMMENT ON COLUMN "t11 decoder".parent.note IS 'note ''quote'' 界';
        CREATE INDEX same_name ON "t11 decoder".parent("SecondKey" DESC NULLS LAST,"first,key") INCLUDE(note) WHERE note IS NOT NULL;
        CREATE TABLE t11_decoder_other.parent(a integer,b integer);
        CREATE INDEX same_name ON t11_decoder_other.parent(a,b);
        CREATE TABLE "t11 decoder".child(a integer,b integer,qty integer);
        ALTER TABLE "t11 decoder".child ADD CONSTRAINT invalid_fk FOREIGN KEY(a,b) REFERENCES "t11 decoder".parent("SecondKey","first,key") MATCH FULL ON UPDATE CASCADE ON DELETE SET NULL(a) DEFERRABLE INITIALLY DEFERRED NOT VALID;
        ALTER TABLE "t11 decoder".child ADD CONSTRAINT no_key CHECK(1>0) NOT VALID;
        CREATE TABLE "t11 decoder".empty_columns();
        INSERT INTO "t11 decoder".parent("first,key","SecondKey") VALUES(7,3);
    "#).await.unwrap();
    let before = target
        .client
        .query_one(
            r#"SELECT last_value,is_called FROM "t11 decoder".parent_id_seq"#,
            &[],
        )
        .await
        .unwrap();
    let before = (before.get::<_, i64>(0), before.get::<_, bool>(1));
    let owner: String = target
        .client
        .query_one("SELECT current_user::text", &[])
        .await
        .unwrap()
        .get(0);
    for table in ["parent", "child", "empty_columns"] {
        for row in target
            .client
            .query(
                include_str!("../../src/postgres/observed_sequences.sql"),
                &[&"t11 decoder", &table],
            )
            .await
            .unwrap()
        {
            postgres::observed::decode_sequence_part(
                &row,
                my2pg::model::SequenceStateObservation::Known {
                    last_value: 1,
                    is_called: false,
                },
            )
            .unwrap();
        }
        for row in target
            .client
            .query(
                include_str!("../../src/postgres/observed_triggers.sql"),
                &[&"t11 decoder", &Some(table)],
            )
            .await
            .unwrap()
        {
            postgres::observed::decode_trigger_part(&row).unwrap();
        }
    }
    let first = postgres::inspect(&mut target.client, "t11 decoder")
        .await
        .unwrap();
    let second = postgres::inspect(&mut target.client, "t11 decoder")
        .await
        .unwrap();
    assert_eq!(
        serde_json::to_value(&first).unwrap(),
        serde_json::to_value(&second).unwrap()
    );
    let parent = first
        .tables
        .iter()
        .find(|table| table.name == "parent")
        .unwrap();
    let observed = parent.observed.as_ref().unwrap();
    assert!(observed.oid > 0);
    assert_eq!(observed.owner, owner);
    assert_eq!(observed.relation_kind, "r");
    assert_eq!(observed.access_method.as_deref(), Some("heap"));
    assert_eq!(observed.persistence, "p");
    assert_eq!(observed.comment.as_deref(), Some("table 'quote' 界"));
    assert!(!observed.row_security_enabled && !observed.row_security_forced);
    assert_eq!(observed.replica_identity, "d");
    let column = |name: &str| {
        observed
            .columns
            .iter()
            .find(|column| column.name == name)
            .unwrap()
    };
    assert_eq!(column("id").identity_mode, "d");
    assert_eq!(column("always_id").identity_mode, "a");
    assert_eq!(column("generated_value").generated_kind, "s");
    assert!(column("generated_value").default_expression.is_none());
    assert!(column("generated_value").generation_expression.is_some());
    assert_eq!(column("matrix").array_dimensions, 2);
    assert_eq!(column("matrix").type_element_oid, 23);
    assert_eq!(column("domain_value").type_kind, "d");
    assert_eq!(column("domain_value").type_base_oid, 23);
    assert_eq!(column("value").type_kind, "e");
    assert_eq!(column("value").type_schema, "t11 decoder");
    assert_eq!(column("value").type_name, "State Type");
    assert_eq!(column("note").comment.as_deref(), Some("note 'quote' 界"));
    assert_eq!(
        column("note").collation_schema.as_deref(),
        Some("pg_catalog")
    );
    assert_eq!(column("note").collation_name.as_deref(), Some("C"));
    assert_eq!(column("note").collation_deterministic, Some(true));
    let parts: Vec<_> = observed
        .index_parts
        .iter()
        .filter(|part| part.index_name == "same_name")
        .collect();
    assert_eq!(parts.len(), 3);
    assert!(parts.iter().all(|part| part.index_schema == "t11 decoder"
        && part.table_oid == observed.oid
        && part.valid
        && part.ready
        && part.live));
    assert_eq!(
        parts.iter().map(|part| part.ordinal).collect::<Vec<_>>(),
        [1, 2, 3]
    );
    assert_eq!(
        parts
            .iter()
            .map(|part| part.column_name.as_deref())
            .collect::<Vec<_>>(),
        [Some("SecondKey"), Some("first,key"), Some("note")]
    );
    assert_eq!(parts[0].column_ordinal, 2);
    assert_eq!(parts[0].descending, Some(true));
    assert_eq!(parts[0].nulls_first, Some(false));
    assert!(parts[0].operator_class_oid.is_some());
    assert!(
        parts[2].included && parts[2].descending.is_none() && parts[2].operator_class_oid.is_none()
    );
    let child = first
        .tables
        .iter()
        .find(|table| table.name == "child")
        .unwrap()
        .observed
        .as_ref()
        .unwrap();
    let fk: Vec<_> = child
        .constraint_parts
        .iter()
        .filter(|part| part.name == "invalid_fk")
        .collect();
    assert_eq!(fk.len(), 2);
    assert_eq!(
        fk.iter().map(|part| part.ordinal).collect::<Vec<_>>(),
        [Some(1), Some(2)]
    );
    assert_eq!(
        fk.iter()
            .map(|part| part.referenced_column.as_deref())
            .collect::<Vec<_>>(),
        [Some("SecondKey"), Some("first,key")]
    );
    assert!(fk.iter().all(|part| !part.validated
        && part.deferrable
        && part.initially_deferred
        && part.referenced_table_oid == Some(observed.oid)
        && part.pk_fk_operator_oid.is_some()));
    assert_eq!(fk[0].match_type, "f");
    assert_eq!(fk[0].update_action, "c");
    assert_eq!(fk[0].delete_action, "n");
    assert_eq!(fk[0].delete_set_columns.as_ref().unwrap(), &["a"]);
    let no_key = child
        .constraint_parts
        .iter()
        .find(|part| part.name == "no_key")
        .unwrap();
    assert!(no_key.ordinal.is_none() && no_key.column_name.is_none() && !no_key.validated);
    let empty = first
        .tables
        .iter()
        .find(|table| table.name == "empty_columns")
        .unwrap()
        .observed
        .as_ref()
        .unwrap();
    assert!(
        empty.columns.is_empty()
            && empty.index_parts.is_empty()
            && empty.constraint_parts.is_empty()
    );
    let encoded = serde_json::to_vec(observed).unwrap();
    assert_eq!(*observed, serde_json::from_slice(&encoded).unwrap());
    let after = target
        .client
        .query_one(
            r#"SELECT last_value,is_called FROM "t11 decoder".parent_id_seq"#,
            &[],
        )
        .await
        .unwrap();
    assert_eq!(before, (after.get::<_, i64>(0), after.get::<_, bool>(1)));
    assert_eq!(
        target
            .client
            .query_one(r#"SELECT COUNT(*) FROM "t11 decoder".parent"#, &[])
            .await
            .unwrap()
            .get::<_, i64>(0),
        1
    );
    assert_eq!(
        target
            .client
            .query_one("SELECT current_setting('transaction_read_only')", &[])
            .await
            .unwrap()
            .get::<_, String>(0),
        "off",
        "inspection transaction must have ended"
    );
    target
        .client
        .batch_execute(r#"DROP SCHEMA "t11 decoder" CASCADE;DROP SCHEMA t11_decoder_other CASCADE"#)
        .await
        .unwrap();
    target.close().await.unwrap();
}

#[tokio::test]
#[ignore = "requires owned PostgreSQL TLS fixture"]
async fn malformed_binary_rows_and_failed_metadata_query_are_errors_not_empty_success() {
    let config: TargetConfig = serde_json::from_value(serde_json::json!({
        "url_env":"MY2PG_POSTGRES_URL","schema":"t11_decoder_error","ca_file":required("MY2PG_TLS_CA")
    })).unwrap();
    let mut target = postgres::connect(&config, &required("MY2PG_POSTGRES_URL"))
        .await
        .unwrap();
    let wrong = target
        .client
        .query_one("SELECT 'not-smallint'::text AS ordinal", &[])
        .await
        .unwrap();
    assert!(postgres::observed::decode_column(&wrong).is_err());
    let missing = target
        .client
        .query_one("SELECT 1::int2 AS ordinal", &[])
        .await
        .unwrap();
    assert!(postgres::observed::decode_column(&missing).is_err());
    assert!(postgres::observed::decode_index_part(&missing).is_err());
    assert!(postgres::observed::decode_constraint_part(&missing).is_err());
    assert!(postgres::observed::decode_trigger_part(&missing).is_err());
    assert!(
        postgres::observed::decode_sequence_part(
            &missing,
            my2pg::model::SequenceStateObservation::Unavailable {
                reason: "select_privilege_denied".into()
            }
        )
        .is_err()
    );
    let transaction = target
        .client
        .build_transaction()
        .read_only(true)
        .start()
        .await
        .unwrap();
    assert!(
        postgres::observed::inspect(&transaction, "t11_decoder_error", "absent")
            .await
            .is_err()
    );
    let error = transaction.batch_execute("SELECT 1/0").await.unwrap_err();
    assert_eq!(error.code().unwrap().code(), "22012");
    let error = postgres::observed::inspect(&transaction, "t11_decoder_error", "absent")
        .await
        .unwrap_err();
    assert_eq!(error.sqlstate.as_deref(), Some("25P02"));
    transaction.rollback().await.unwrap();
    let absent = postgres::inspect(&mut target.client, "t11_decoder_error")
        .await
        .unwrap();
    assert!(!absent.schema_exists && absent.tables.is_empty());
    target.close().await.unwrap();
}

#[tokio::test]
#[ignore = "requires owned PostgreSQL TLS fixture"]
async fn public_inspector_preserves_sequence_state_denial_and_global_event_headers() {
    use my2pg::model::SequenceStateObservation;
    use std::collections::BTreeSet;
    let config: TargetConfig = serde_json::from_value(serde_json::json!({
        "url_env":"MY2PG_POSTGRES_URL","schema":"t11_states","ca_file":required("MY2PG_TLS_CA")
    }))
    .unwrap();
    let mut target = postgres::connect(&config, &required("MY2PG_POSTGRES_URL"))
        .await
        .unwrap();
    target.client.batch_execute(r#"
        CREATE SCHEMA t11_states; CREATE SCHEMA t11_states_other;
        CREATE SEQUENCE t11_states_other."comma,quote""seq" START 7 INCREMENT 3 CACHE 4 MINVALUE 0 MAXVALUE 99;
        CREATE TABLE t11_states.rows(id bigint DEFAULT nextval('t11_states_other."comma,quote""seq"'::regclass));
        CREATE ROLE t11_state_reader;
        GRANT USAGE ON SCHEMA t11_states,t11_states_other TO t11_state_reader;
        GRANT SELECT ON t11_states.rows TO t11_state_reader;
        CREATE FUNCTION t11_states_other.noop() RETURNS event_trigger LANGUAGE plpgsql AS $$ BEGIN RETURN; END $$;
        CREATE EVENT TRIGGER t11_decoder_event ON ddl_command_end EXECUTE FUNCTION t11_states_other.noop();
        ALTER EVENT TRIGGER t11_decoder_event DISABLE;
    "#).await.unwrap();
    let catalog = postgres::inspect(&mut target.client, "t11_states")
        .await
        .unwrap();
    let observed = catalog.tables[0].observed.as_ref().unwrap();
    assert!(!observed.sequence_parts.is_empty());
    for seq in &observed.sequence_parts {
        assert_eq!(seq.sequence_schema, "t11_states_other");
        assert_eq!(seq.sequence_name, "comma,quote\"seq");
        assert_eq!(seq.increment_by, 3);
        assert_eq!(seq.cache_size, 4);
        assert_eq!(seq.bound_column_ordinal, 1);
        assert_eq!(seq.ownership_dependency, None);
        assert_eq!(
            seq.state,
            SequenceStateObservation::Known {
                last_value: 7,
                is_called: false
            }
        );
    }
    let events = catalog.event_triggers.as_ref().unwrap();
    let actual_count: i64 = target
        .client
        .query_one("SELECT COUNT(*) FROM pg_catalog.pg_event_trigger", &[])
        .await
        .unwrap()
        .get(0);
    assert_eq!(
        events
            .iter()
            .map(|e| e.trigger_oid)
            .collect::<BTreeSet<_>>()
            .len() as i64,
        actual_count
    );
    let event = events
        .iter()
        .find(|e| e.trigger_name == "t11_decoder_event")
        .unwrap();
    assert_eq!(event.scope, "event");
    assert_eq!(event.enabled, "D");
    assert_eq!(event.function_schema, "t11_states_other");
    assert_eq!(event.table_oid, None);
    assert_eq!(event.internal, None);
    target
        .client
        .batch_execute("SET ROLE t11_state_reader")
        .await
        .unwrap();
    let denied = postgres::inspect(&mut target.client, "t11_states")
        .await
        .unwrap();
    let denied_parts = &denied.tables[0].observed.as_ref().unwrap().sequence_parts;
    assert_eq!(denied_parts.len(), observed.sequence_parts.len());
    for seq in denied_parts {
        assert!(!seq.can_select && !seq.can_update && !seq.can_alter);
        assert_eq!(
            seq.state,
            SequenceStateObservation::Unavailable {
                reason: "select_privilege_denied".into()
            }
        );
    }
    let denied_error = target
        .client
        .query_one(
            r#"SELECT last_value,is_called FROM t11_states_other."comma,quote""seq""#,
            &[],
        )
        .await
        .unwrap_err();
    assert_eq!(denied_error.code().unwrap().code(), "42501");
    target.client.batch_execute("RESET ROLE").await.unwrap();
    let state = target
        .client
        .query_one(
            r#"SELECT last_value,is_called FROM t11_states_other."comma,quote""seq""#,
            &[],
        )
        .await
        .unwrap();
    assert_eq!(
        (state.get::<_, i64>(0), state.get::<_, bool>(1)),
        (7, false)
    );
    let absent = postgres::inspect(&mut target.client, "t11_states_missing")
        .await
        .unwrap();
    assert!(!absent.schema_exists && absent.tables.is_empty());
    assert!(
        absent
            .event_triggers
            .unwrap()
            .iter()
            .any(|e| e.trigger_oid == event.trigger_oid)
    );
    target.client.batch_execute("DROP EVENT TRIGGER t11_decoder_event;DROP SCHEMA t11_states CASCADE;DROP SCHEMA t11_states_other CASCADE;DROP ROLE t11_state_reader").await.unwrap();
    target.close().await.unwrap();
}
