use my2pg::{config::TargetConfig, model::*, postgres};
use mysql_async::prelude::Queryable;
use std::env;

fn required(name: &str) -> String {
    env::var(name).unwrap_or_else(|_| panic!("missing {name}"))
}
fn config() -> TargetConfig {
    serde_json::from_value(serde_json::json!({
        "url_env":"MY2PG_POSTGRES_URL", "schema":"t11_monotonic",
        "ca_file":required("MY2PG_TLS_CA")
    }))
    .unwrap()
}
fn table(kind: &str, name: &str, next: Option<u64>) -> TablePlan {
    TablePlan {
        id: "t_0123456789abcdef".into(),
        source_name: "source".into(),
        target_schema: "t11_monotonic".into(),
        target_name: name.into(),
        engine: "InnoDB".into(),
        is_view: false,
        estimated_rows: None,
        next_auto_increment: next,
        columns: vec![ColumnPlan {
            source_name: "id".into(),
            target_name: "id".into(),
            source_type: "int".into(),
            target_type: kind.into(),
            kind: ValueKind::SignedInteger,
            nullable: false,
            default_sql: None,
            identity: true,
            generated_expression: None,
            copy: true,
            transform: None,
            charset: None,
            enum_labels: vec![],
            set_labels: vec![],
            comment: None,
        }],
        primary_key: vec![],
        structure: SchemaExpectations::default(),
    }
}
fn sql(table: &TablePlan) -> String {
    postgres::sequences::adjustment_sql(table, &table.columns[0]).unwrap()
}
async fn state(client: &tokio_postgres::Client, sequence: &str) -> (i64, bool) {
    let row = client
        .query_one(&format!("SELECT last_value,is_called FROM {sequence}"), &[])
        .await
        .unwrap();
    (row.get(0), row.get(1))
}
async fn sequence(client: &tokio_postgres::Client, relation: &str) -> String {
    client
        .query_one("SELECT pg_get_serial_sequence($1,'id')", &[&relation])
        .await
        .unwrap()
        .get(0)
}

#[tokio::test]
#[ignore = "requires owned Oracle MySQL/PostgreSQL TLS fixtures"]
async fn actual_adjustment_never_rewinds_and_next_insert_uses_exact_bound() {
    let target = postgres::connect(&config(), &required("MY2PG_POSTGRES_URL"))
        .await
        .unwrap();
    target
        .client
        .batch_execute("CREATE SCHEMA t11_monotonic")
        .await
        .unwrap();
    for kind in ["smallint", "integer", "bigint"] {
        let name = "rows '$my2pg_seq$\\";
        let relation = postgres::qualified("t11_monotonic", name);
        target
            .client
            .batch_execute(&format!(
                "CREATE TABLE {relation}(id {kind} GENERATED BY DEFAULT AS IDENTITY)"
            ))
            .await
            .unwrap();
        let sequence = sequence(&target.client, &relation).await;
        for (rows, last, called, source_next, expected_state, expected_insert) in [
            ("", 1, false, None, (1, false), 1),
            ("", 1, false, Some(42), (42, false), 42),
            ("(-3),(-1)", 1, false, None, (1, false), 1),
            ("(23)", 1, false, Some(1), (24, false), 24),
            ("(23)", 4, true, Some(42), (42, false), 42),
            ("(1),(2)", 150, true, Some(42), (150, true), 151),
            ("(1)", 100, false, Some(42), (100, false), 100),
            ("(1)", 41, true, Some(42), (41, true), 42),
        ] {
            target
                .client
                .batch_execute(&format!(
                    "TRUNCATE {relation}; SELECT pg_catalog.setval('{}'::regclass,{last},{called})",
                    sequence.replace('\'', "''")
                ))
                .await
                .unwrap();
            if !rows.is_empty() {
                target
                    .client
                    .batch_execute(&format!("INSERT INTO {relation} VALUES {rows}"))
                    .await
                    .unwrap();
            }
            let planned = table(kind, name, source_next);
            target.client.batch_execute(&sql(&planned)).await.unwrap();
            assert_eq!(
                state(&target.client, &sequence).await,
                expected_state,
                "{kind}/{rows}/{last}/{called}"
            );
            let row = target
                .client
                .query_one(
                    &format!("INSERT INTO {relation} DEFAULT VALUES RETURNING id::bigint"),
                    &[],
                )
                .await
                .unwrap();
            assert_eq!(row.get::<_, i64>(0), expected_insert);
        }
        target
            .client
            .batch_execute(&format!("DROP TABLE {relation}"))
            .await
            .unwrap();
    }
    target
        .client
        .batch_execute("DROP SCHEMA t11_monotonic")
        .await
        .unwrap();
    target.close().await.unwrap();
}

#[tokio::test]
#[ignore = "requires owned Oracle MySQL/PostgreSQL TLS fixtures"]
async fn fresh_sequence_drift_exhaustion_and_external_users_fail_before_setval() {
    let target = postgres::connect(&config(), &required("MY2PG_POSTGRES_URL"))
        .await
        .unwrap();
    target.client.batch_execute("CREATE SCHEMA t11_monotonic; CREATE TABLE t11_monotonic.rows(id smallint GENERATED BY DEFAULT AS IDENTITY)").await.unwrap();
    let relation = "t11_monotonic.rows";
    let sequence = sequence(&target.client, relation).await;
    let planned = table("smallint", "rows", Some(42));
    for (change, restore) in [
        ("INCREMENT BY 2", "INCREMENT BY 1"),
        ("CACHE 4", "CACHE 1"),
        ("CYCLE", "NO CYCLE"),
        ("MINVALUE 0", "MINVALUE 1"),
        ("MAXVALUE 100", "MAXVALUE 32767"),
    ] {
        target
            .client
            .batch_execute(&format!("ALTER SEQUENCE {sequence} {change}"))
            .await
            .unwrap();
        let before = state(&target.client, &sequence).await;
        let error = target
            .client
            .batch_execute(&sql(&planned))
            .await
            .unwrap_err();
        assert_eq!(error.code().unwrap().code(), "55000");
        assert_eq!(state(&target.client, &sequence).await, before);
        target
            .client
            .batch_execute(&format!("ALTER SEQUENCE {sequence} {restore}"))
            .await
            .unwrap();
    }
    for (rows, source_next, last, called) in [
        ("(32767)", Some(1), 1, false),
        ("", Some(u64::MAX), 1, false),
        ("", Some(1), 32767, true),
    ] {
        target
            .client
            .batch_execute(&format!(
                "TRUNCATE {relation}; SELECT setval('{sequence}',{last},{called})"
            ))
            .await
            .unwrap();
        if !rows.is_empty() {
            target
                .client
                .batch_execute(&format!("INSERT INTO {relation} VALUES {rows}"))
                .await
                .unwrap();
        }
        let before = state(&target.client, &sequence).await;
        let error = target
            .client
            .batch_execute(&sql(&table("smallint", "rows", source_next)))
            .await
            .unwrap_err();
        assert_eq!(error.code().unwrap().code(), "22003");
        assert_eq!(state(&target.client, &sequence).await, before);
    }
    target.client.batch_execute(&format!("TRUNCATE {relation}; SELECT setval('{sequence}',1,false); CREATE TABLE t11_monotonic.outside(id smallint DEFAULT nextval('{sequence}'))")).await.unwrap();
    let error = target
        .client
        .batch_execute(&sql(&planned))
        .await
        .unwrap_err();
    assert_eq!(error.code().unwrap().code(), "55000");
    assert_eq!(state(&target.client, &sequence).await, (1, false));
    target.client.batch_execute("DROP TABLE t11_monotonic.outside; ALTER TABLE t11_monotonic.rows ALTER COLUMN id SET GENERATED ALWAYS").await.unwrap();
    let error = target
        .client
        .batch_execute(&sql(&planned))
        .await
        .unwrap_err();
    assert_eq!(error.code().unwrap().code(), "55000");
    target
        .client
        .batch_execute(
            "DROP TABLE t11_monotonic.rows; CREATE TABLE t11_monotonic.rows(id smallserial)",
        )
        .await
        .unwrap();
    assert!(target.client.batch_execute(&sql(&planned)).await.is_err());
    target
        .client
        .batch_execute("DROP TABLE t11_monotonic.rows; DROP SCHEMA t11_monotonic")
        .await
        .unwrap();
    target.close().await.unwrap();
}

#[tokio::test]
#[ignore = "requires owned Oracle MySQL/PostgreSQL TLS fixtures"]
async fn sequence_privileges_table_lock_and_nontransactional_effect_are_observable() {
    let target = postgres::connect(&config(), &required("MY2PG_POSTGRES_URL"))
        .await
        .unwrap();
    let locker = postgres::connect(&config(), &required("MY2PG_POSTGRES_URL"))
        .await
        .unwrap();
    target.client.batch_execute("CREATE SCHEMA t11_monotonic; CREATE TABLE t11_monotonic.rows(id bigint GENERATED BY DEFAULT AS IDENTITY); CREATE ROLE t11_sequence_writer; GRANT USAGE ON SCHEMA t11_monotonic TO t11_sequence_writer; GRANT ALL ON t11_monotonic.rows TO t11_sequence_writer").await.unwrap();
    let planned = table("bigint", "rows", Some(42));
    let sequence = sequence(&target.client, "t11_monotonic.rows").await;
    for grant in ["SELECT", "UPDATE"] {
        target.client.batch_execute(&format!("REVOKE ALL ON SEQUENCE {sequence} FROM t11_sequence_writer; GRANT {grant} ON SEQUENCE {sequence} TO t11_sequence_writer; SET ROLE t11_sequence_writer")).await.unwrap();
        let error = target
            .client
            .batch_execute(&sql(&planned))
            .await
            .unwrap_err();
        assert_eq!(error.code().unwrap().code(), "42501");
        target.client.batch_execute("RESET ROLE").await.unwrap();
        assert_eq!(state(&target.client, &sequence).await, (1, false));
    }
    target.client.batch_execute(&format!("GRANT SELECT,UPDATE ON SEQUENCE {sequence} TO t11_sequence_writer; SET ROLE t11_sequence_writer")).await.unwrap();
    target.client.batch_execute(&sql(&planned)).await.unwrap();
    target.client.batch_execute("RESET ROLE").await.unwrap();
    assert_eq!(
        state(&target.client, &sequence).await,
        (42, false),
        "a nonowner with actual privileges can update"
    );
    locker
        .client
        .batch_execute("BEGIN; LOCK TABLE t11_monotonic.rows IN ACCESS EXCLUSIVE MODE")
        .await
        .unwrap();
    let error = target
        .client
        .batch_execute(&sql(&table("bigint", "rows", Some(100))))
        .await
        .unwrap_err();
    assert_eq!(error.code().unwrap().code(), "55P03");
    assert_eq!(state(&target.client, &sequence).await, (42, false));
    locker.client.batch_execute("ROLLBACK").await.unwrap();
    target.client.batch_execute("BEGIN").await.unwrap();
    target
        .client
        .batch_execute(&sql(&table("bigint", "rows", Some(100))))
        .await
        .unwrap();
    target.client.batch_execute("ROLLBACK").await.unwrap();
    assert_eq!(
        state(&target.client, &sequence).await,
        (100, false),
        "setval survives rollback; no whole-step rollback claim"
    );
    target.client.batch_execute("DROP TABLE t11_monotonic.rows; DROP SCHEMA t11_monotonic; DROP ROLE t11_sequence_writer").await.unwrap();
    locker.close().await.unwrap();
    target.close().await.unwrap();
}

#[tokio::test]
#[ignore = "requires owned Oracle MySQL/PostgreSQL TLS fixtures"]
async fn real_runner_adjusts_existing_identity_and_preserves_disabled_state() {
    let directory = env::temp_dir().join(format!("my2pg-t11-sequence-run-{}", std::process::id()));
    std::fs::create_dir(&directory).unwrap();
    let mut config:my2pg::config::MigrationConfig=serde_json::from_value(serde_json::json!({
        "version":1,"source":{"url_env":"MY2PG_MYSQL_URL","ca_file":required("MY2PG_TLS_CA"),"consistency":"frozen"},
        "target":{"url_env":"MY2PG_POSTGRES_URL","ca_file":required("MY2PG_TLS_CA"),"schema":"t11_monotonic"},
        "migration":{"batch_rows":2,"batch_bytes":4096,"max_row_bytes":1024,"memory_bytes":262144},
        "tables":{"include":["T11MonotonicSource"],"rename":[{"source":"T11MonotonicSource","target":"rows"}]},
        "report":{"directory":directory.join("runs"),"console":"json","progress":"never"}
    })).unwrap();
    let mut source = my2pg::mysql::connect(&config.source, &required("MY2PG_MYSQL_ROOT_URL"), 1024)
        .await
        .unwrap();
    source.query_drop("CREATE TABLE T11MonotonicSource(id INT NOT NULL AUTO_INCREMENT PRIMARY KEY); INSERT INTO T11MonotonicSource VALUES(1),(2); ALTER TABLE T11MonotonicSource AUTO_INCREMENT=42").await.unwrap();
    let target = postgres::connect(&config.target, &required("MY2PG_POSTGRES_URL"))
        .await
        .unwrap();
    async fn run(
        config: &my2pg::config::MigrationConfig,
        directory: &std::path::Path,
        label: &str,
    ) {
        let path = directory.join(format!("{label}.toml"));
        std::fs::write(&path, toml::to_string(config).unwrap()).unwrap();
        let output = tokio::task::spawn_blocking(move || {
            std::process::Command::new(env!("CARGO_BIN_EXE_my2pg"))
                .arg("run")
                .arg(path)
                .args(["--output", "json", "--progress", "never"])
                .output()
                .unwrap()
        })
        .await
        .unwrap();
        assert_eq!(
            output.status.code(),
            Some(0),
            "{label}: {} {}",
            String::from_utf8_lossy(&output.stdout),
            String::from_utf8_lossy(&output.stderr)
        );
    }
    run(&config, &directory, "new").await;
    let sequence = sequence(&target.client, "t11_monotonic.rows").await;
    assert_eq!(state(&target.client, &sequence).await, (42, false));
    target.client.batch_execute(&format!("CREATE ROLE t11_no_sequence_lock LOGIN PASSWORD 'fixture-only'; GRANT USAGE ON SCHEMA t11_monotonic TO t11_no_sequence_lock; GRANT SELECT,INSERT ON t11_monotonic.rows TO t11_no_sequence_lock; GRANT SELECT,UPDATE ON SEQUENCE {sequence} TO t11_no_sequence_lock")).await.unwrap();
    let mut restricted_url = url::Url::parse(&required("MY2PG_POSTGRES_URL")).unwrap();
    restricted_url.set_username("t11_no_sequence_lock").unwrap();
    restricted_url.set_password(Some("fixture-only")).unwrap();
    let mut restricted = postgres::connect(&config.target, restricted_url.as_str())
        .await
        .unwrap();
    let observed = postgres::inspect(&mut restricted.client, &config.target.schema)
        .await
        .unwrap();
    assert_eq!(observed.tables[0].can_lock, Some(false));
    let seq_parts = &observed.tables[0].observed.as_ref().unwrap().sequence_parts;
    assert!(
        seq_parts
            .iter()
            .all(|part| part.can_select && part.can_update)
    );
    let source_catalog = my2pg::mysql::inspect(&mut source).await.unwrap();
    let mut denied = config.clone();
    denied.migration.mode = my2pg::config::MigrationMode::DataOnly;
    denied.target.on_existing = my2pg::config::ExistingPolicy::Append;
    let my2pg::plan::PlanError::Blocked(diagnostics) =
        my2pg::plan::build(&denied, &source_catalog, &observed).unwrap_err()
    else {
        panic!("expected positive lock privilege refusal")
    };
    assert!(
        diagnostics
            .iter()
            .any(|diagnostic| diagnostic.code == "TARGET_SEQUENCE_LOCK_PRIVILEGE")
    );
    denied.target.url_env = Some("MY2PG_T11_NO_LOCK_URL".into());
    let denied_path = directory.join("denied.toml");
    std::fs::write(&denied_path, toml::to_string(&denied).unwrap()).unwrap();
    let output = tokio::task::spawn_blocking(move || {
        std::process::Command::new(env!("CARGO_BIN_EXE_my2pg"))
            .env("MY2PG_T11_NO_LOCK_URL", restricted_url.as_str())
            .arg("run")
            .arg(denied_path)
            .args(["--output", "json", "--progress", "never"])
            .output()
            .unwrap()
    })
    .await
    .unwrap();
    assert!(!output.status.success());
    assert!(String::from_utf8_lossy(&output.stderr).contains("TARGET_SEQUENCE_LOCK_PRIVILEGE"));
    assert_eq!(
        target
            .client
            .query_one("SELECT count(*) FROM t11_monotonic.rows", &[])
            .await
            .unwrap()
            .get::<_, i64>(0),
        2
    );
    assert_eq!(state(&target.client, &sequence).await, (42, false));
    restricted.close().await.unwrap();
    target.client.batch_execute(&format!("DELETE FROM t11_monotonic.rows; INSERT INTO t11_monotonic.rows VALUES(99); SELECT setval('{sequence}',150,true)")).await.unwrap();
    config.migration.mode = my2pg::config::MigrationMode::DataOnly;
    config.target.on_existing = my2pg::config::ExistingPolicy::Append;
    run(&config, &directory, "append").await;
    assert_eq!(state(&target.client, &sequence).await, (150, true));
    let rows = target
        .client
        .query("SELECT id FROM t11_monotonic.rows ORDER BY id", &[])
        .await
        .unwrap();
    assert_eq!(
        rows.iter().map(|r| r.get::<_, i32>(0)).collect::<Vec<_>>(),
        [1, 2, 99]
    );
    target
        .client
        .batch_execute(&format!(
            "DELETE FROM t11_monotonic.rows WHERE id IN (1,2); SELECT setval('{sequence}',1,false)"
        ))
        .await
        .unwrap();
    run(&config, &directory, "append-reset").await;
    assert_eq!(
        state(&target.client, &sequence).await,
        (100, false),
        "data-only reset must account for existing target rows"
    );
    let next: i64 = target
        .client
        .query_one("SELECT nextval($1::text::regclass)", &[&sequence])
        .await
        .unwrap()
        .get(0);
    assert_eq!(next, 100);
    let rows = target
        .client
        .query("SELECT id FROM t11_monotonic.rows ORDER BY id", &[])
        .await
        .unwrap();
    assert_eq!(
        rows.iter().map(|r| r.get::<_, i32>(0)).collect::<Vec<_>>(),
        [1, 2, 99]
    );
    target
        .client
        .batch_execute(&format!("SELECT setval('{sequence}',1,false)"))
        .await
        .unwrap();
    config.target.on_existing = my2pg::config::ExistingPolicy::Truncate;
    config.migration.reset_sequences = false;
    run(&config, &directory, "preserve").await;
    assert_eq!(state(&target.client, &sequence).await, (1, false));
    let error = target
        .client
        .batch_execute("INSERT INTO t11_monotonic.rows DEFAULT VALUES")
        .await
        .unwrap_err();
    assert_eq!(
        error.code().unwrap().code(),
        "23505",
        "preserving state is not a claim that generation exceeds imported rows"
    );
    let mut warnings = std::collections::BTreeSet::new();
    for entry in std::fs::read_dir(directory.join("runs")).unwrap() {
        let report: serde_json::Value = serde_json::from_slice(
            &std::fs::read(entry.unwrap().path().join("report.json")).unwrap(),
        )
        .unwrap();
        assert_eq!(report["verification"]["status"], "complete");
        for diagnostic in report["diagnostics"].as_array().unwrap() {
            warnings.insert(diagnostic["code"].as_str().unwrap().to_owned());
        }
    }
    assert!(warnings.contains("SEQUENCE_NONTRANSACTIONAL"));
    assert!(warnings.contains("SEQUENCE_STATE_PRESERVED"));
    source
        .query_drop("DROP TABLE T11MonotonicSource")
        .await
        .unwrap();
    target
        .client
        .batch_execute("DROP TABLE t11_monotonic.rows; DROP SCHEMA t11_monotonic; DROP ROLE t11_no_sequence_lock")
        .await
        .unwrap();
    target.close().await.unwrap();
    source.disconnect().await.unwrap();
    std::fs::remove_dir_all(directory).unwrap();
}
